use super::*;

pub fn init(cx: &mut App) {
    cx.bind_keys([
        KeyBinding::new("enter", Enter, Some(KEY_CONTEXT)),
        KeyBinding::new("backspace", Backspace, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-backspace", Backspace, Some(KEY_CONTEXT)),
        KeyBinding::new("alt-backspace", BackspaceWord, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-backspace", BackspaceLine, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-backspace", BackspaceLine, Some(KEY_CONTEXT)),
        KeyBinding::new("delete", DeleteForward, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-delete", DeleteForward, Some(KEY_CONTEXT)),
        KeyBinding::new("alt-delete", DeleteWord, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-delete", DeleteLine, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-delete", DeleteLine, Some(KEY_CONTEXT)),
        KeyBinding::new("left", MoveLeft, Some(KEY_CONTEXT)),
        KeyBinding::new("right", MoveRight, Some(KEY_CONTEXT)),
        KeyBinding::new("alt-left", MoveLeftWord, Some(KEY_CONTEXT)),
        KeyBinding::new("alt-right", MoveRightWord, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-left", MoveLineStart, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-right", MoveLineEnd, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-left", MoveLineStart, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-right", MoveLineEnd, Some(KEY_CONTEXT)),
        KeyBinding::new("home", MoveLineStart, Some(KEY_CONTEXT)),
        KeyBinding::new("end", MoveLineEnd, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-up", MoveDocumentStart, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-down", MoveDocumentEnd, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-up", MoveDocumentStart, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-down", MoveDocumentEnd, Some(KEY_CONTEXT)),
        KeyBinding::new("up", MoveUp, Some(KEY_CONTEXT)),
        KeyBinding::new("down", MoveDown, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-left", SelectLeft, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-right", SelectRight, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-up", SelectUp, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-down", SelectDown, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-alt-left", SelectLeftWord, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-alt-right", SelectRightWord, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-secondary-left", SelectLineStart, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-secondary-right", SelectLineEnd, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-cmd-left", SelectLineStart, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-cmd-right", SelectLineEnd, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-home", SelectLineStart, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-end", SelectLineEnd, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-secondary-up", SelectDocumentStart, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-secondary-down", SelectDocumentEnd, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-cmd-up", SelectDocumentStart, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-cmd-down", SelectDocumentEnd, Some(KEY_CONTEXT)),
        KeyBinding::new("tab", IndentLine, Some(KEY_CONTEXT)),
        KeyBinding::new("shift-tab", UnindentLine, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-shift-t", InsertTable, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-shift-t", InsertTable, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-a", SelectAll, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-a", SelectAll, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-c", Copy, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-c", Copy, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-x", Cut, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-x", Cut, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-v", Paste, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-v", Paste, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-shift-v", PastePlain, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-shift-v", PastePlain, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-1", SetMarkerBlank, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-1", SetMarkerBlank, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-2", SetMarkerCheckbox, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-2", SetMarkerCheckbox, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-3", SetMarkerBullet, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-3", SetMarkerBullet, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-4", SetMarkerNumbered, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-4", SetMarkerNumbered, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-b", ToggleBold, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-b", ToggleBold, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-i", ToggleItalic, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-i", ToggleItalic, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-shift-x", ToggleStrikethrough, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-shift-x", ToggleStrikethrough, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-j", ToggleHeading, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-j", ToggleHeading, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-l", ToggleStatus, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-l", ToggleStatus, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-s", ToggleStartDate, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-s", ToggleStartDate, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-e", ToggleEndDate, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-e", ToggleEndDate, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-r", ToggleRepeat, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-r", ToggleRepeat, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-shift-s", RemoveStartDate, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-shift-s", RemoveStartDate, Some(KEY_CONTEXT)),
        KeyBinding::new("cmd-shift-e", RemoveEndDate, Some(KEY_CONTEXT)),
        KeyBinding::new("secondary-shift-e", RemoveEndDate, Some(KEY_CONTEXT)),
        KeyBinding::new(
            "ctrl-secondary-space",
            ShowCharacterPalette,
            Some(KEY_CONTEXT),
        ),
    ]);
}
