use crate::catalog::{Catalogs, Entry, TargetConfig, PLURAL_CATEGORIES};
use anyhow::{Context, Result};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;

/// Emits `res/values[-<qualifier>]/strings.xml` (+ `<plurals>`) per locale and
/// a generated `L10n.kt` mapping catalog keys onto resource ids.
///
/// Plain entries keep literal `{name}` placeholders (substituted by `L10n.t`);
/// plural entries rewrite `{count}` to `%1$d` for `getQuantityString`.
pub fn run(catalogs: &Catalogs, config: &TargetConfig) -> Result<()> {
    for locale in &catalogs.locales {
        let entries = &catalogs.by_locale[&locale.code];
        if locale.code != "en" && entries.is_empty() {
            continue;
        }
        let dir = config.android_res_dir.join(values_dir(&locale.code));
        fs::create_dir_all(&dir)?;

        let mut xml = String::from("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
        xml.push_str("<!-- Generated by l10n-gen from app/l10n — do not edit by hand. -->\n");
        xml.push_str("<resources xmlns:tools=\"http://schemas.android.com/tools\">\n");
        // Only English (the default `values/`) declares the app label.
        if locale.code == "en" {
            xml.push_str("    <string name=\"app_name\" translatable=\"false\">KnotQ</string>\n");
        }
        for (key, entry) in entries {
            // Skip keys unknown to English (validate blocks this anyway).
            if !catalogs.english().contains_key(key) {
                continue;
            }
            let name = resource_name(key);
            match entry {
                Entry::Plain(pattern) => {
                    // aapt only format-checks strings unless told otherwise;
                    // literal '%' in copy must opt out instead of doubling,
                    // because getString(id) without args returns the raw value.
                    let mut attributes = String::new();
                    if pattern.contains('%') {
                        attributes.push_str(" formatted=\"false\"");
                    }
                    // Catalogs intentionally allow a locale to omit a key and
                    // fall back to English. Tell Android lint that the default
                    // resource is complete by design; otherwise every newly
                    // extracted English-only string becomes a release error.
                    if locale.code == "en"
                        && !key.starts_with("web.")
                        && catalogs.locales.iter().any(|other| {
                            other.code != "en" && !catalogs.by_locale[&other.code].contains_key(key)
                        })
                    {
                        attributes.push_str(" tools:ignore=\"MissingTranslation\"");
                    }
                    // Website copy is present in the shared catalog so the
                    // generator can keep one key space, but it is never an
                    // Android surface and should not create translation
                    // obligations in Android resource lint.
                    if key.starts_with("web.") {
                        attributes.push_str(" translatable=\"false\"");
                    }
                    writeln!(
                        xml,
                        "    <string name=\"{name}\"{attributes}>{}</string>",
                        escape_android(pattern)
                    )?;
                }
                Entry::Plural(forms) => {
                    writeln!(xml, "    <plurals name=\"{name}\">")?;
                    // Android's resource loader has a fixed set of quantity
                    // categories. A catalog may intentionally omit a
                    // category because its runtime callers never use that
                    // quantity; use `other` as the same fallback Android
                    // would otherwise apply at runtime, while keeping every
                    // generated resource lint-complete.
                    for category in PLURAL_CATEGORIES {
                        let Some(pattern) = android_plural_pattern(forms, category) else {
                            continue;
                        };
                        let ignore_implied_quantity = if pattern.contains("{count}") {
                            ""
                        } else {
                            // Some valid copy deliberately omits the number
                            // (for example, “Every day” or a one-item
                            // confirmation). Android lint cannot see the
                            // call-site invariant and flags those forms when
                            // the locale maps one to multiple numbers.
                            " tools:ignore=\"ImpliedQuantity\""
                        };
                        writeln!(
                            xml,
                            "        <item quantity=\"{category}\"{ignore_implied_quantity}>{}</item>",
                            escape_android(&pattern.replace("{count}", "%1$d"))
                        )?;
                    }
                    writeln!(xml, "    </plurals>")?;
                }
            }
        }
        xml.push_str("</resources>\n");
        let path = dir.join("strings.xml");
        fs::write(&path, xml).with_context(|| format!("writing {}", path.display()))?;
    }

    write_l10n_kt(catalogs, config)?;
    println!(
        "wrote Android resources under {} and {}",
        config.android_res_dir.display(),
        config.android_l10n_kt.display()
    );
    Ok(())
}

fn android_plural_pattern<'a>(
    forms: &'a BTreeMap<String, String>,
    category: &str,
) -> Option<&'a str> {
    forms
        .get(category)
        .or_else(|| forms.get("other"))
        .map(String::as_str)
}

/// Android resource directory qualifier for a locale code, including the
/// legacy codes old resource qualifiers still require.
fn values_dir(code: &str) -> String {
    match code {
        "en" => "values".to_string(),
        "he" => "values-iw".to_string(),
        "id" => "values-in".to_string(),
        "zh-Hans" => "values-b+zh+Hans".to_string(),
        "zh-Hant" => "values-b+zh+Hant".to_string(),
        other => match other.split_once('-') {
            Some((lang, region)) => format!("values-{lang}-r{region}"),
            None => format!("values-{other}"),
        },
    }
}

fn resource_name(key: &str) -> String {
    key.replace(['.', '-'], "_")
}

fn escape_android(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('\'', "\\'")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}

fn write_l10n_kt(catalogs: &Catalogs, config: &TargetConfig) -> Result<()> {
    let mut plain_keys = Vec::new();
    let mut plural_keys = Vec::new();
    for (key, entry) in catalogs.english() {
        match entry {
            Entry::Plain(_) => plain_keys.push(key),
            Entry::Plural(_) => plural_keys.push(key),
        }
    }

    let header = r#"// Generated by l10n-gen from app/l10n — do not edit by hand.
package com.enigmadux.knotq

import android.content.Context

/** Catalog-key lookup over the generated string resources. */
object L10n {
"#;
    let mut kt = String::from(header);
    // Explicit type arguments: an empty mapOf(...) can't infer K/V, which bites
    // us for real the first time a catalog ships zero plural entries.
    kt.push_str("    private val strings = mapOf<String, Int>(\n");
    for key in &plain_keys {
        writeln!(kt, "        \"{key}\" to R.string.{},", resource_name(key))?;
    }
    kt.push_str("    )\n\n");
    kt.push_str("    private val plurals = mapOf<String, Int>(\n");
    for key in &plural_keys {
        writeln!(kt, "        \"{key}\" to R.plurals.{},", resource_name(key))?;
    }
    kt.push_str("    )\n");
    kt.push_str(
        r#"
    fun t(context: Context, key: String): String =
        strings[key]?.let { context.getString(it) } ?: key

    fun t(context: Context, key: String, args: Map<String, String>): String {
        var value = t(context, key)
        for ((name, arg) in args) value = value.replace("{$name}", arg)
        return value
    }

    fun plural(context: Context, key: String, count: Int): String =
        plurals[key]?.let { context.resources.getQuantityString(it, count, count) } ?: key
}
"#,
    );

    if let Some(parent) = config.android_l10n_kt.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&config.android_l10n_kt, kt)
        .with_context(|| format!("writing {}", config.android_l10n_kt.display()))
}

#[cfg(test)]
mod tests {
    use super::android_plural_pattern;
    use std::collections::BTreeMap;

    #[test]
    fn missing_android_quantity_categories_use_other_without_changing_fallback() {
        let forms = BTreeMap::from([
            ("one".to_string(), "{count} item".to_string()),
            ("other".to_string(), "{count} items".to_string()),
        ]);

        assert_eq!(android_plural_pattern(&forms, "one"), Some("{count} item"));
        assert_eq!(
            android_plural_pattern(&forms, "many"),
            Some("{count} items")
        );
    }
}
