use crate::catalog::{Catalogs, Entry, TargetConfig};
use anyhow::{Context, Result};
use std::fmt::Write as _;
use std::fs;

/// Emits `res/values[-<qualifier>]/strings.xml` (+ `<plurals>`) per locale and
/// a generated `L10n.kt` mapping catalog keys onto resource ids.
///
/// Plain entries keep literal `{name}` placeholders (substituted by `L10n.t`);
/// plural entries rewrite `{count}` to `%1$d` for `getQuantityString`.
pub fn run(catalogs: &Catalogs, config: &TargetConfig) -> Result<()> {
    for locale in &catalogs.locales {
        let entries = &catalogs.by_locale[&locale.code];
        if locale.code != "en" && entries.is_empty() {
            continue;
        }
        let dir = config.android_res_dir.join(values_dir(&locale.code));
        fs::create_dir_all(&dir)?;

        let mut xml = String::from("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
        xml.push_str("<!-- Generated by l10n-gen from app/l10n — do not edit by hand. -->\n");
        xml.push_str("<resources>\n");
        // Only English (the default `values/`) declares the app label.
        if locale.code == "en" {
            xml.push_str("    <string name=\"app_name\" translatable=\"false\">KnotQ</string>\n");
        }
        for (key, entry) in entries {
            // Skip keys unknown to English (validate blocks this anyway).
            if !catalogs.english().contains_key(key) {
                continue;
            }
            let name = resource_name(key);
            match entry {
                Entry::Plain(pattern) => {
                    // aapt only format-checks strings unless told otherwise;
                    // literal '%' in copy must opt out instead of doubling,
                    // because getString(id) without args returns the raw value.
                    let formatted = if pattern.contains('%') { " formatted=\"false\"" } else { "" };
                    writeln!(
                        xml,
                        "    <string name=\"{name}\"{formatted}>{}</string>",
                        escape_android(pattern)
                    )?;
                }
                Entry::Plural(forms) => {
                    writeln!(xml, "    <plurals name=\"{name}\">")?;
                    for (category, pattern) in forms {
                        writeln!(
                            xml,
                            "        <item quantity=\"{category}\">{}</item>",
                            escape_android(&pattern.replace("{count}", "%1$d"))
                        )?;
                    }
                    writeln!(xml, "    </plurals>")?;
                }
            }
        }
        xml.push_str("</resources>\n");
        let path = dir.join("strings.xml");
        fs::write(&path, xml).with_context(|| format!("writing {}", path.display()))?;
    }

    write_l10n_kt(catalogs, config)?;
    println!(
        "wrote Android resources under {} and {}",
        config.android_res_dir.display(),
        config.android_l10n_kt.display()
    );
    Ok(())
}

/// Android resource directory qualifier for a locale code, including the
/// legacy codes old resource qualifiers still require.
fn values_dir(code: &str) -> String {
    match code {
        "en" => "values".to_string(),
        "he" => "values-iw".to_string(),
        "id" => "values-in".to_string(),
        "zh-Hans" => "values-b+zh+Hans".to_string(),
        "zh-Hant" => "values-b+zh+Hant".to_string(),
        other => match other.split_once('-') {
            Some((lang, region)) => format!("values-{lang}-r{region}"),
            None => format!("values-{other}"),
        },
    }
}

fn resource_name(key: &str) -> String {
    key.replace(['.', '-'], "_")
}

fn escape_android(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('\'', "\\'")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
}

fn write_l10n_kt(catalogs: &Catalogs, config: &TargetConfig) -> Result<()> {
    let mut plain_keys = Vec::new();
    let mut plural_keys = Vec::new();
    for (key, entry) in catalogs.english() {
        match entry {
            Entry::Plain(_) => plain_keys.push(key),
            Entry::Plural(_) => plural_keys.push(key),
        }
    }

    let header = r#"// Generated by l10n-gen from app/l10n — do not edit by hand.
package com.enigmadux.knotq

import android.content.Context

/** Catalog-key lookup over the generated string resources. */
object L10n {
"#;
    let mut kt = String::from(header);
    // Explicit type arguments: an empty mapOf(...) can't infer K/V, which bites
    // us for real the first time a catalog ships zero plural entries.
    kt.push_str("    private val strings = mapOf<String, Int>(\n");
    for key in &plain_keys {
        writeln!(kt, "        \"{key}\" to R.string.{},", resource_name(key))?;
    }
    kt.push_str("    )\n\n");
    kt.push_str("    private val plurals = mapOf<String, Int>(\n");
    for key in &plural_keys {
        writeln!(kt, "        \"{key}\" to R.plurals.{},", resource_name(key))?;
    }
    kt.push_str("    )\n");
    kt.push_str(
        r#"
    fun t(context: Context, key: String): String =
        strings[key]?.let { context.getString(it) } ?: key

    fun t(context: Context, key: String, args: Map<String, String>): String {
        var value = t(context, key)
        for ((name, arg) in args) value = value.replace("{$name}", arg)
        return value
    }

    fun plural(context: Context, key: String, count: Int): String =
        plurals[key]?.let { context.resources.getQuantityString(it, count, count) } ?: key
}
"#,
    );

    if let Some(parent) = config.android_l10n_kt.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&config.android_l10n_kt, kt)
        .with_context(|| format!("writing {}", config.android_l10n_kt.display()))
}
