use crate::catalog::{Catalogs, Entry, TargetConfig};
use anyhow::{Context, Result};
use serde_json::{json, Map, Value};
use std::fs;

/// Emits `website/js/i18n/<locale>.js` catalog scripts plus `locales.js`
/// (the registry the language picker and the runtime read). The hand-written
/// runtime `website/js/i18n.js` consumes these via `window.__KNOTQ_L10N`.
pub fn run(catalogs: &Catalogs, config: &TargetConfig) -> Result<()> {
    fs::create_dir_all(&config.website_i18n_dir)?;

    for locale in &catalogs.locales {
        let entries = &catalogs.by_locale[&locale.code];
        if locale.code != "en" && entries.is_empty() {
            continue;
        }
        let mut map = Map::new();
        for (key, entry) in entries {
            if !catalogs.english().contains_key(key) {
                continue;
            }
            let value = match entry {
                Entry::Plain(pattern) => Value::String(pattern.clone()),
                Entry::Plural(forms) => Value::Object(
                    forms
                        .iter()
                        .map(|(category, pattern)| {
                            (category.clone(), Value::String(pattern.clone()))
                        })
                        .collect(),
                ),
            };
            map.insert(key.clone(), value);
        }
        let script = format!(
            "// Generated by l10n-gen from app/l10n — do not edit by hand.\n\
             window.__KNOTQ_L10N = window.__KNOTQ_L10N || {{}};\n\
             window.__KNOTQ_L10N[{code}] = {catalog};\n",
            code = json!(locale.code),
            catalog = serde_json::to_string_pretty(&Value::Object(map))?,
        );
        let path = config.website_i18n_dir.join(format!("{}.js", locale.code));
        fs::write(&path, script).with_context(|| format!("writing {}", path.display()))?;
    }

    let registry: Vec<Value> = catalogs
        .locales
        .iter()
        .filter(|l| l.code == "en" || !catalogs.by_locale[&l.code].is_empty())
        .map(|l| json!({ "code": l.code, "native": l.native, "rtl": l.rtl }))
        .collect();
    let script = format!(
        "// Generated by l10n-gen from app/l10n — do not edit by hand.\n\
         window.__KNOTQ_L10N_LOCALES = {};\n",
        serde_json::to_string_pretty(&Value::Array(registry))?
    );
    let path = config.website_i18n_dir.join("locales.js");
    fs::write(&path, script).with_context(|| format!("writing {}", path.display()))?;
    println!("wrote website catalogs under {}", config.website_i18n_dir.display());
    Ok(())
}
